# Debian 13 (trixie) removed ntp and recommends ntpsec or chrony.
# I use ntpsec
- name: Install NTPSec
  package:
    name: ntpsec
    state: present
- name: Configure ntp servers
  copy:
    dest: /etc/ntpsec/ntp.conf
    mode: "0644"
    content: |
      server 0.pool.ntp.org
      server 1.pool.ntp.org
      server 2.pool.ntp.org
      server 3.pool.ntp.org
- name: Restart ntp service
  service:
    name: ntp
    state: restarted
